#!/bin/sh
#
# Update get_iplayer
#
(wget -qO - "`wget -qO - 'https://api.github.com/repos/get-iplayer/get_iplayer/releases/latest' | jq -r .tarball_url`" | tar -zxf - && cd get-iplayer* && install -m 755 -t /usr/local/bin ./get_iplayer ./get_iplayer.cgi && cd $OLDPWD && rm -rf get-iplayer*) 2>> /var/log/get_iplayer_update.log
